name = "CoinfectionSimulator"
uuid = "2df91e3f-da06-5362-a6fe-03772f2e14c9"
authors = ["July Pilowsky <japilo@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CoinfectionSimulator = "7d77d32e-a319-475a-a7da-1ed1d9bcafc7"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
DataFrames = "1.7"
Distributions = "0.25"
Documenter = "1"
julia = "1.11"